[build]
  # Directory with the frontend files
  publish = "."
  
  # Build command (if needed)
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all requests to /api/* to your Firebase Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for Firebase
[[headers]]
  for = "/js/firebase-*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables for build
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
